sonar.projectKey=amrutha-juice-backend
sonar.projectName=Amrutha Juice Backend
sonar.projectVersion=2.0.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js,**/coverage/**

sonar.sourceEncoding=UTF-8
